### ISSUE TITLE
need port 8080/tcp open in firewalld 

### ISSUE THREAD

**Issue by dustymabe** [dustymabe/summit-2018-container-lab#22] opened 2018-04-20 22:32 UTC

**Comment by dustymabe** [comment] 2018-04-20 22:33
many of our labs tell us we can use the browser to connec to :8080, but that port isn't open in the firewall on this instance.

**Comment by tchughesiv** [comment] 2018-04-20 22:33
I noticed the same, although the AMI build appears to open it. I haven’t checked in AWS though.

**Comment by dustymabe** [comment] 2018-04-20 22:42
even after I opened 8080 using firewalld I can't connect to the app. I wonder if podman has issues with firewalld vs plain iptables.. this needs some investigation.

**Comment by scollier** [comment] 2018-04-21 04:04
the AWS security group is open:

```

Custom TCP Rule | TCP | 8080 | 0.0.0.0/0
-- | -- | -- | --

```

**Comment by whitel** [comment] 2018-04-24 20:12
ok.. so the issue is we need to modify:  /etc/sysconfig/iptables with
```bash
-A INPUT -p tcp -m state --state NEW -m tcp --dport 8080 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 8443 -j ACCEPT
```
right after the ssh line and we need to do this before start-oc. As a result, I would do it in the ami directly.
/me thinks that is all the ports we need

**Comment by dustymabe** [comment] 2018-04-24 21:32
just tested.. everything seems to work if we don't have firewalld on the system. according to podman devs it doesn't support firewalld yet. @scollier can you remove firewalld from the system and related ansible for configuring ports?

**Comment by scollier** [comment] 2018-04-24 22:36
https://github.com/scollier/ansible-ami-builder/pull/19 /cc @dustymabe @whitel @tchughesiv

**Closed** 2018-04-25 13:42 UTC
Labels: AMI
